server:
    port: 8080

spring:
    datasource:
      druid:
        name: test
        url: jdbc:mysql://192.168.1.108:3306/shuiquan?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

        # --------------------------Druid----------------------------
        # 过滤器
#        filters: stat
#        initial-size: 5
#        max-active: 20
#        min-idle: 5
#        max-wait: 60000
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        validation-query: select 1
#        testWhileIdle: true
#        test-on-borrow: false
#        test-on-return: false
#        pool-prepared-statements: true
#        max-open-prepared-statements: 20
    mvc:
      static-path-pattern: /static/**

#######################################################
#
# freemarker 静态资源配置
#
#######################################################
# 设定ftl文件路径
    freemarker:
      template-loader-path: classpath:/templates
      # 关闭缓存，即时更新，上线生产环境需要改为true
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
mybatis:
  mapper-locations: classpath:mapper/*.xml







#        web-stat-filter:
#          enabled: false
#          url-pattern:
#          exclusions:
#          session-stat-enable:
#          session-stat-max-count:
#          principal-cookie-name:
#          principal-session-name:
#          profile-enable:
#        stat-view-servlet:
#          enabled: false
#          url-pattern:
#          reset-enable:
#          login-username:
#          login-password:
#          allow:
#          deny:
#        aop-patterns:

  # MyBatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.bfs.po

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql




#logging:
#  level:
#    org: ERROR
#    net: ERROR
#    com: ERROR
#    # \u5F00\u542FMySQL JDBC \u9A71\u52A8\u7684\u65E5\u5FD7
#    MySQL: DEBUG


 # \u9A71\u52A8\u914D\u7F6E\u4FE1\u606F



#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url = jdbc:mysql://127.0.0.1:3306/water
#spring.datasource.username = root
#spring.datasource.password = 1234
#spring.datasource.driverClassName = com.mysql.jdbc.Driver
#
## \u8FDE\u63A5\u6C60\u7684\u914D\u7F6E\u4FE1\u606F
## \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
#spring.datasource.initialSize=5
#spring.datasource.minIdle=5
#spring.datasource.maxActive=20
## \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
#spring.datasource.maxWait=60000
## \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#spring.datasource.timeBetweenEvictionRunsMillis=60000
## \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
## \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
## \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899
#spring.datasource.filters=stat,wall,log4j
## \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000